### ISSUE TITLE
atexit woes

### ISSUE THREAD

**Issue by fwsGonzo** [lionkor/commandline#30]
Hey, nice library. I am wondering if it makes sense to move the atexit function restoring termios to just the destructor of the commandline? I have a server that handles SIGINT in order to gracefully store stuff to disk and then immediately _exit in order to avoid having to tearing down multi-gigabytes of structures. Guess it's just one of those weird cases.

For now I am just calling the atexit handler in the destructor :+1:

**Comment by lionkor** [comment]
Hi,thanks for using the library! Thats definitely a good idea :) If you want, you can make a PR for it, otherwise I'll implement it coming week :)On Feb 19, 2023 1:32 PM, Alf-André Walla ***@***.***> wrote:

Hey, nice library. I am wondering if it makes sense to move the atexit function restoring termios to just the destructor of the commandline? I have a server that handles SIGINT in order to gracefully store stuff to disk and then immediately _exit in order to avoid having to tearing down multi-gigabytes of structures. Guess it's just one of those weird cases.

For now I am just calling the atexit handler in the destructor 👍

**Comment by lionkor** [comment]
Sorry, took a bit longer :)
